
export default new Map([
["src/content/blog/en/welcome-to-astro.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Fen%2Fwelcome-to-astro.mdx&astroContentModuleFlag=true")],
["src/content/blog/es/bienvenido-a-astro.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Fes%2Fbienvenido-a-astro.mdx&astroContentModuleFlag=true")],
["src/content/blog/ja/astro-e-youkoso.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Fja%2Fastro-e-youkoso.mdx&astroContentModuleFlag=true")],
["src/content/blog/en/machine-learning-beginners-guide.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Fen%2Fmachine-learning-beginners-guide.mdx&astroContentModuleFlag=true")],
["src/content/blog/en/future-of-artificial-intelligence.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Fen%2Ffuture-of-artificial-intelligence.mdx&astroContentModuleFlag=true")],
["src/content/blog/en/web-development-trends-2024.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Fen%2Fweb-development-trends-2024.mdx&astroContentModuleFlag=true")],
["src/content/blog/en/cybersecurity-best-practices.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Fen%2Fcybersecurity-best-practices.mdx&astroContentModuleFlag=true")],
["src/content/blog/en/cloud-computing-evolution.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Fen%2Fcloud-computing-evolution.mdx&astroContentModuleFlag=true")],
["src/content/blog/en/blockchain-beyond-cryptocurrency.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Fen%2Fblockchain-beyond-cryptocurrency.mdx&astroContentModuleFlag=true")],
["src/content/blog/en/devops-automation-strategies.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Fen%2Fdevops-automation-strategies.mdx&astroContentModuleFlag=true")],
["src/content/blog/en/mobile-app-development-flutter.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Fen%2Fmobile-app-development-flutter.mdx&astroContentModuleFlag=true")],
["src/content/blog/en/quantum-computing-basics.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Fen%2Fquantum-computing-basics.mdx&astroContentModuleFlag=true")],
["src/content/blog/en/iot-smart-cities.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Fen%2Fiot-smart-cities.mdx&astroContentModuleFlag=true")],
["src/content/blog/en/data-science-python.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Fen%2Fdata-science-python.mdx&astroContentModuleFlag=true")],
["src/content/blog/en/edge-computing-revolution.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Fen%2Fedge-computing-revolution.mdx&astroContentModuleFlag=true")]]);
		