<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="2.0"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:rss="http://purl.org/rss/1.0/"
                xmlns:dc="http://purl.org/dc/elements/1.1/"
                xmlns:content="http://purl.org/rss/1.0/modules/content/"
                xmlns:atom="http://www.w3.org/2005/Atom">
	<xsl:output method="html" version="1.0" encoding="UTF-8" indent="yes"/>
	<xsl:template match="/">
		<html xmlns="http://www.w3.org/1999/xhtml">
			<head>
				<title>RSS Feed</title>
				<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
				<style type="text/css">
					body {
						font-family: 'Inter', -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
						font-size: 14px;
						color: #333;
						margin: 0;
						padding: 40px;
						background: #f8fafc;
					}
					.container {
						max-width: 1000px;
						margin: 0 auto;
						background: #fff;
						padding: 40px;
						border-radius: 12px;
						box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -1px rgba(0, 0, 0, 0.06);
					}
					h1 {
						color: #1e293b;
						font-size: 28px;
						margin-bottom: 20px;
						display: flex;
						align-items: center;
						gap: 10px;
					}
					p {
						color: #64748b;
						line-height: 1.6;
						margin-bottom: 30px;
					}
					table {
						width: 100%;
						border-collapse: collapse;
						margin-top: 20px;
					}
					th {
						text-align: left;
						background: #f1f5f9;
						padding: 12px 16px;
						color: #475569;
						font-weight: 600;
						border-bottom: 2px solid #e2e8f0;
					}
					td {
						padding: 12px 16px;
						border-bottom: 1px solid #f1f5f9;
						word-break: break-all;
					}
					tr:hover td {
						background: #f8fafc;
					}
					a {
						color: #2563eb;
						text-decoration: none;
					}
					a:hover {
						text-decoration: underline;
					}
					.footer {
						margin-top: 40px;
						text-align: center;
						color: #94a3b8;
						font-size: 12px;
					}
				</style>
			</head>
			<body>
				<div class="container">
					<h1><xsl:value-of select="/rss/channel/title"/></h1>
					<p><xsl:value-of select="/rss/channel/description"/></p>
					<p>Total posts in this feed: <xsl:value-of select="count(/rss/channel/item)"/></p>
					<table>
						<thead>
							<tr>
								<th width="70%">Title</th>
								<th width="30%">Publication Date</th>
							</tr>
						</thead>
						<tbody>
							<xsl:for-each select="/rss/channel/item">
								<tr>
									<td>
										<xsl:variable name="itemURL"><xsl:value-of select="link"/></xsl:variable>
										<a href="{$itemURL}" target="_blank" rel="noopener">
											<xsl:value-of select="title"/>
										</a>
									</td>
									<td>
										<xsl:value-of select="pubDate"/>
									</td>
								</tr>
							</xsl:for-each>
						</tbody>
					</table>

					<div class="footer">
						Generated by Astro Batavia - A Modern Multi-language Blog
					</div>
				</div>
			</body>
		</html>
	</xsl:template>
</xsl:stylesheet>
