<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="2.0"
                xmlns:html="http://www.w3.org/TR/REC-html40"
                xmlns:image="http://www.google.com/schemas/sitemap-image/1.1"
                xmlns:sitemap="http://www.sitemaps.org/schemas/sitemap/0.9"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
  <xsl:output method="html" version="1.0" encoding="UTF-8" indent="yes"/>
  <xsl:template match="/">
    <html xmlns="http://www.w3.org/1999/xhtml">
      <head>
        <title>XML Sitemap | Astro Batavia</title>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <style type="text/css">
          body {
            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen-Sans, Ubuntu, Cantarell, "Helvetica Neue", sans-serif;
            color: #333;
            margin: 0;
            background: #f4f7f9;
          }
          #intro {
            background-color: #2c3e50;
            padding: 30px 40px;
            color: #fff;
          }
          #intro h1 {
            margin: 0 0 10px 0;
          }
          #intro p {
            margin: 0;
            opacity: 0.8;
            font-size: 14px;
          }
          #intro a {
            color: #3498db;
          }
          #content {
            padding: 40px;
          }
          table {
            width: 100%;
            border-collapse: collapse;
            background: #fff;
            box-shadow: 0 1px 3px rgba(0,0,0,0.1);
            border-radius: 8px;
            overflow: hidden;
          }
          th {
            background-color: #fcfcfc;
            text-align: left;
            padding: 15px;
            font-size: 13px;
            font-weight: 600;
            color: #7f8c8d;
            border-bottom: 1px solid #eee;
          }
          td {
            padding: 15px;
            font-size: 14px;
            border-bottom: 1px solid #f9f9f9;
          }
          tr:hover td {
            background-color: #fdfdfd;
          }
          tr:last-child td {
            border-bottom: none;
          }
          a {
            color: #3498db;
            text-decoration: none;
          }
          a:hover {
            text-decoration: underline;
          }
          .count {
            float: right;
            background: #3498db;
            color: white;
            padding: 2px 8px;
            border-radius: 12px;
            font-size: 12px;
          }
        </style>
      </head>
      <body>
        <div id="intro">
          <h1>XML Sitemap</h1>
          <p>
            Generated by Astro Batavia. This is an XML Sitemap, meant for consumption by search engines like Google or Bing.
            You can find more information about XML sitemaps on <a href="http://sitemaps.org">sitemaps.org</a>.
          </p>
        </div>
        <div id="content">
          <p>Total URLs: <xsl:value-of count="sitemap:urlset/sitemap:url | sitemap:sitemapindex/sitemap:sitemap" select="count(.)"/></p>
          <table>
            <tr>
              <th>URL</th>
              <xsl:if test="sitemap:urlset/sitemap:url/sitemap:lastmod">
                <th>Last Modified</th>
              </xsl:if>
              <xsl:if test="sitemap:urlset/sitemap:url/sitemap:changefreq">
                <th>Change Freq.</th>
              </xsl:if>
              <xsl:if test="sitemap:urlset/sitemap:url/sitemap:priority">
                <th>Priority</th>
              </xsl:if>
            </tr>
            <xsl:for-each select="sitemap:urlset/sitemap:url">
              <tr>
                <td>
                  <a href="{sitemap:loc}"><xsl:value-of select="sitemap:loc"/></a>
                </td>
                <xsl:if test="sitemap:lastmod">
                  <td><xsl:value-of select="sitemap:lastmod"/></td>
                </xsl:if>
                <xsl:if test="sitemap:changefreq">
                  <td><xsl:value-of select="sitemap:changefreq"/></td>
                </xsl:if>
                <xsl:if test="sitemap:priority">
                  <td><xsl:value-of select="sitemap:priority"/></td>
                </xsl:if>
              </tr>
            </xsl:for-each>
            <xsl:for-each select="sitemap:sitemapindex/sitemap:sitemap">
              <tr>
                <td>
                  <a href="{sitemap:loc}"><xsl:value-of select="sitemap:loc"/></a>
                </td>
                <xsl:if test="sitemap:lastmod">
                  <td><xsl:value-of select="sitemap:lastmod"/></td>
                </xsl:if>
              </tr>
            </xsl:for-each>
          </table>
        </div>
      </body>
    </html>
  </xsl:template>
</xsl:stylesheet>
