<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="2.0"
                xmlns:html="http://www.w3.org/TR/REC-html40"
                xmlns:sitemap="http://www.sitemaps.org/schemas/sitemap/0.9"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
	<xsl:output method="html" version="1.0" encoding="UTF-8" indent="yes"/>
	<xsl:template match="/">
		<html xmlns="http://www.w3.org/1999/xhtml">
			<head>
				<title>XML Sitemap</title>
				<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
				<style type="text/css">
					body {
						font-family: 'Inter', -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
						font-size: 14px;
						color: #333;
						margin: 0;
						padding: 40px;
						background: #f8fafc;
					}
					.container {
						max-width: 1000px;
						margin: 0 auto;
						background: #fff;
						padding: 40px;
						border-radius: 12px;
						box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -1px rgba(0, 0, 0, 0.06);
					}
					h1 {
						color: #1e293b;
						font-size: 28px;
						margin-bottom: 20px;
						display: flex;
						align-items: center;
						gap: 10px;
					}
					p {
						color: #64748b;
						line-height: 1.6;
						margin-bottom: 30px;
					}
					table {
						width: 100%;
						border-collapse: collapse;
						margin-top: 20px;
					}
					th {
						text-align: left;
						background: #f1f5f9;
						padding: 12px 16px;
						color: #475569;
						font-weight: 600;
						border-bottom: 2px solid #e2e8f0;
					}
					td {
						padding: 12px 16px;
						border-bottom: 1px solid #f1f5f9;
						word-break: break-all;
					}
					tr:hover td {
						background: #f8fafc;
					}
					a {
						color: #2563eb;
						text-decoration: none;
					}
					a:hover {
						text-decoration: underline;
					}
					.footer {
						margin-top: 40px;
						text-align: center;
						color: #94a3b8;
						font-size: 12px;
					}
					.badge {
						display: inline-block;
						padding: 2px 8px;
						border-radius: 4px;
						font-size: 11px;
						font-weight: 600;
						text-transform: uppercase;
					}
					.badge-high { background: #dcfce7; color: #166534; }
					.badge-med { background: #fef9c3; color: #854d0e; }
					.badge-low { background: #f1f5f9; color: #475569; }
				</style>
			</head>
			<body>
				<div class="container">
					<h1>XML Sitemap</h1>
					<p>This is a human-readable XML Sitemap, meant for search engines like Google or Bing.</p>

					<xsl:if test="sitemap:sitemapindex">
						<p>Total sitemaps in this index: <xsl:value-of select="count(sitemap:sitemapindex/sitemap:sitemap)"/></p>
						<table>
							<thead>
								<tr>
									<th>Sitemap URL</th>
									<th>Last Modified</th>
								</tr>
							</thead>
							<tbody>
								<xsl:for-each select="sitemap:sitemapindex/sitemap:sitemap">
									<tr>
										<td>
											<xsl:variable name="sitemapURL"><xsl:value-of select="sitemap:loc"/></xsl:variable>
											<a href="{$sitemapURL}"><xsl:value-of select="sitemap:loc"/></a>
										</td>
										<td><xsl:value-of select="sitemap:lastmod"/></td>
									</tr>
								</xsl:for-each>
							</tbody>
						</table>
					</xsl:if>

					<xsl:if test="sitemap:urlset">
						<p>Total URLs in this segment: <xsl:value-of select="count(sitemap:urlset/sitemap:url)"/></p>
						<table>
							<thead>
								<tr>
									<th width="70%">URL</th>
									<th width="10%">Priority</th>
									<th width="10%">Changefreq</th>
									<th width="10%">Last Modified</th>
								</tr>
							</thead>
							<tbody>
								<xsl:for-each select="sitemap:urlset/sitemap:url">
									<tr>
										<td>
											<xsl:variable name="itemURL"><xsl:value-of select="sitemap:loc"/></xsl:variable>
											<a href="{$itemURL}"><xsl:value-of select="sitemap:loc"/></a>
										</td>
										<td>
											<span class="badge">
												<xsl:attribute name="class">
													<xsl:choose>
														<xsl:when test="sitemap:priority &gt;= 0.8">badge badge-high</xsl:when>
														<xsl:when test="sitemap:priority &gt;= 0.5">badge badge-med</xsl:when>
														<xsl:otherwise>badge badge-low</xsl:otherwise>
													</xsl:choose>
												</xsl:attribute>
												<xsl:value-of select="sitemap:priority"/>
											</span>
										</td>
										<td><xsl:value-of select="sitemap:changefreq"/></td>
										<td><xsl:value-of select="sitemap:lastmod"/></td>
									</tr>
								</xsl:for-each>
							</tbody>
						</table>
					</xsl:if>

					<div class="footer">
						Generated by Astro Batavia - A Modern Multi-language Blog
					</div>
				</div>
			</body>
		</html>
	</xsl:template>
</xsl:stylesheet>
