import fs from 'fs/promises';

/**
 * @returns {import('astro').AstroIntegration}
 */
export default function sitemapHandler() {
  return {
    name: 'sitemap-handler',
    hooks: {
      'astro:build:done': async ({ dir }) => {
        try {
          // The base names generated by @astrojs/sitemap
          const indexPath = new URL('sitemap-base-index.xml', dir);
          const sitemap0Path = new URL('sitemap-base-0.xml', dir);
          const targetPath = new URL('sitemap.xml', dir);

          const sitemap0Exists = await fs.access(sitemap0Path).then(() => true).catch(() => false);

          if (sitemap0Exists) {
            // 1. Read the content from the first sitemap part
            let content = await fs.readFile(sitemap0Path, 'utf-8');
            
            // 2. Fix formatting and validation issues
            
            // A. Remove unused namespaces that Astro adds by default but are empty here
            // This prevents validation warnings about unused namespaces.
            content = content.replace(/ xmlns:news="[^"]*"/g, '');
            content = content.replace(/ xmlns:image="[^"]*"/g, '');
            content = content.replace(/ xmlns:video="[^"]*"/g, '');
            
            // B. Fix lastmod format: convert 2026-05-13T00:00:00.000Z to 2026-05-13
            // Standard sitemaps prefer YYYY-MM-DD for simple daily/weekly changes.
            content = content.replace(/<lastmod>([^<T]+)T[^<]*<\/lastmod>/g, '<lastmod>$1</lastmod>');
            
            // C. Pretty-print: Add newlines between tags for readability
            // We use a more careful approach to avoid breaking the XML declaration
            content = content.replace(/>\s*</g, '>\n<');
            
            // D. Trim any leading/trailing whitespace to ensure it starts with <?xml
            content = content.trim();

            // 3. Write the final sitemap.xml
            await fs.writeFile(targetPath, content + '\n');
            console.log('✅ Created consolidated and validated sitemap.xml');

            // 4. Clean up ALL temporary files
            await fs.unlink(sitemap0Path).catch(() => {});
            await fs.unlink(indexPath).catch(() => {});
            
            // Also try to remove any other sitemap-base-*.xml files if they exist
            // (Just in case the site ever grows beyond 10k entries)
            const files = await fs.readdir(dir);
            for (const file of files) {
              if (file.startsWith('sitemap-base-') && file.endsWith('.xml')) {
                await fs.unlink(new URL(file, dir)).catch(() => {});
              }
            }
          }
        } catch (error) {
          console.error('❌ Error refactoring sitemap:', error);
        }
      },
    },
  };
}
