import fs from 'fs/promises';

/**
 * @returns {import('astro').AstroIntegration}
 */
export default function sitemapHandler() {
  return {
    name: 'sitemap-handler',
    hooks: {
      'astro:build:done': async ({ dir }) => {
        try {
          // The base names generated by @astrojs/sitemap
          const indexPath = new URL('sitemap-index.xml', dir);
          const sitemap0Path = new URL('sitemap-0.xml', dir);
          const targetPath = new URL('sitemap.xml', dir);

          const sitemap0Exists = await fs.access(sitemap0Path).then(() => true).catch(() => false);

          if (sitemap0Exists) {
            // 1. Read the content from the first sitemap part
            let content = await fs.readFile(sitemap0Path, 'utf-8');
            
            // 2. Fix formatting and validation issues
            
            // A. Standardize the urlset wrapper and namespaces to match exact specifications
            content = content.replace(
              /<urlset[^>]*>/,
              '<urlset xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.sitemaps.org/schemas/sitemap/0.9 http://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd" xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:xhtml="http://www.w3.org/1999/xhtml">'
            );
            
            // B. Fix lastmod format: convert 2026-05-13T00:00:00.000Z to 2026-05-13
            // Standard sitemaps prefer YYYY-MM-DD for simple daily/weekly changes.
            content = content.replace(/<lastmod>([^<T]+)T[^<]*<\/lastmod>/g, '<lastmod>$1</lastmod>');
            
            // D. Trim any leading/trailing whitespace to ensure it starts with <?xml
            content = content.trim();

            // 3. Write the final sitemap.xml
            await fs.writeFile(targetPath, content + '\n');
            console.log('✅ Created consolidated and validated sitemap.xml');

            // 4. Clean up ALL temporary files
            await fs.unlink(sitemap0Path).catch(() => {});
            await fs.unlink(indexPath).catch(() => {});
            
            // Also try to remove any other sitemap-*.xml files if they exist
            // (Just in case the site ever grows beyond 10k entries)
            const files = await fs.readdir(dir);
            for (const file of files) {
              if (file.startsWith('sitemap-') && file.endsWith('.xml')) {
                await fs.unlink(new URL(file, dir)).catch(() => {});
              }
            }
          }
        } catch (error) {
          console.error('❌ Error refactoring sitemap:', error);
        }
      },
    },
  };
}
